[build-system]
requires = [
    "setuptools>=80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.MichiganLetterToLandlordReRet"
version = "1.0.1"
description = "DIY tool for writing a Letter to Landlord (Security Deposit)"
readme = "README.md"
authors = [
    { name = "Brett Harrison", email = "harrison.brett.m@gmail.com" },
]
dependencies = [
    "docassemble.AssemblyLine @ git+https://github.com/SuffolkLITLab/docassemble-AssemblyLine.git@main",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.urls]
Homepage = "https://michiganlegalhelp.org/resources/housing"

[tool.setuptools.packages.find]
where = [
    ".",
]
